# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatroom-frontend
  template:
    metadata:
      labels:
        app: chatroom-frontend
    spec:
      containers:
        - name: chatroom-frontend
          image: chatroom-frontend
          ports:
            - containerPort: 3000
